### ISSUE TITLE
Accept optional settings to configure plugin behavior per event

### ISSUE THREAD

**Issue by brandonaaron** [jquery/jquery-mousewheel#120]
I wanted to go ahead and create an issue to discuss this feature in. Some of the initial discussions (and reasons for this feature) have happened in #36. There is already some progress on this feature in the 4.0.x branch.

I think it'd be useful to extend the behavior of the plugin via settings. It'd be possible to create plugins for the plugin (like a throttling plugin) with the ability to pass settings. It'd look like this:

```
$(...).on('mousewheel', { mousewheel: { debounce: { leading: true, trailing: false, maxDelay: 500 } }, fn);
```

The one thing that I don't like about this is that it feels too noisy. However, I think it is probably best to prefix the settings with "mousewheel" so that we reduce the potential for conflicts.

The initial plugins that I have built are: throttle, debounce, and intent. There are sensible defaults for these plugins so you could enable them by simply passing true like this:

```
$(...).on('mousewheel', { mousewheel: { intent: true } }, fn);
```

**Comment by dmethvin** [comment]
@brandonaaron do you think this is still worthwhile?

**Comment by brandonaaron** [comment]
I still find it an interesting approach to solving some often requested features and then some. Particularly the intent and debounce/throttle plugins.
