### ISSUE TITLE
Not working on Windows.

### ISSUE THREAD

**Issue by macgera** [jquery/jquery-mousewheel#122]
Hello, have some code:

    $('body').on("DOMMouseScroll mousewheel wheel", function(event, delta){
        event.preventDefault();

        if (!isAnimating() && Math.abs(delta) > 20) {
            if (delta < 0 && !isLast()) {
                $("#nextpage").trigger("click");
            }
            else if (delta > 0 && !isFirst()) {
                $("#prevpage").trigger("click");
            }
        }
    });

but, this is not working in any browser on windows. Where i got mistake? Any ideas to help please?

**Comment by macgera** [comment]
Why you close issue? Your answer not resolve the problem. :)

**Comment by scottgonzalez** [comment]
@h0ward was pointing out that your example code uses a function handler that expects the delta values as a parameter. As the README says, the delta values are now provided as properties of the `event` object.

If you're using the current version (3.1.12) and you're reading the deltas from the `event` parameter and you're still having problems, please provided a full reduced test case (you can use http://jsbin.com or http://jsfiddle.net) showing the problem, along with an explanation of what you expect to happen and what is happening.

**Comment by macgera** [comment]
I have no time for this now, but later i show problem using fiddle. And i think make new issue, or update this. :)

**Comment by scottgonzalez** [comment]
You can just update this ticket and we can reopen once there's sufficient details. Thanks.
