### ISSUE TITLE
Change mousewheel to wheel

### ISSUE THREAD

**Issue by lukeapage** [jquery/jquery-mousewheel#128]
Since wheel is the standardised event, this plugin should allow you to write for the event in the standardised form and patch to that.

**Comment by dmethvin** [comment]
It would be a very different interface, perhaps it could be piled on top of what is here but I would lean towards a clean implementation of just the jQuery special event interface for `wheel`. I don't know whether a change that big  merits just a major version bump to 4.0 or an entirely different plugin. Are you interested in working on it?

**Comment by lukeapage** [comment]
No, sorry I have too many other things on my plate.. it was mainly to note that we should polyfill the standard event name and then be able to remove this plugin depending on browser support, rather than invent a new interface that will always differ from what the browsers give us natively. I understand its a breaking change etc.

**Comment by dmethvin** [comment]
Remember that this plugin and its interface was built before the standard was defined, so there was no reinvention going on. 

I agree in principle about polyfilling, and even doing it below jQuery when possible. If that was done I definitely think it would be best as a separate project and not part of this plugin.

**Comment by louisremi** [comment]
There are already numerous jquery plugins that ployfill the `wheel` event out there (I did write [mine](https://github.com/louisremi/jquery.wheel.js/blob/master/src/jquery.wheel.js) before searching on Github). Maybe we should gather a list of these plugins, pick one and move it to the jquery org (w/ author consent) or create a new one from the best ideas out there.

Also, if this plugin lives in a different repo, do you think jquery should support two different wheel related plugins?

**Comment by dmethvin** [comment]
Well, jquery-mousewheel is heavily used so there's no issue with continuing to have it here, it really doesn't need a lot of maintenance. If there's a better `wheel` event polyfill or special events hook we could host that as well, and again I wouldn't expect a lot of maintenance required for it since the behavior is defined by the spec and we won't be adorning it with nonstandard features or behaviors. Or we can just change the README here to point to what we think is now a better solution.

**Comment by louisremi** [comment]
Fair enough.

I did a quick search using the keywords *jquery* and *wheel* on github, npm, bower and jquery's plugin registry. I found three plugins (not as much as I expected):
- [jMouseWheel](https://github.com/letrunghieu/jMouseWheel) ([sources](https://github.com/letrunghieu/jMouseWheel/blob/master/src/jMouseWheel.js)), which doesn't use the jquery's special events API
- [jquery-wheel](https://github.com/mzgol/jquery-wheel) ([sources](https://github.com/mzgol/jquery-wheel/blob/master/src/jquery.wheel.js)), which uses browser-sniffing and seems to polyfill the native event as well
- [jquery.wheel.js](https://github.com/louisremi/jquery.wheel.js) ([sources](https://github.com/louisremi/jquery.wheel.js/blob/master/src/jquery.wheel.js)), my plugin, which doesn't provide a `.wheel()` method yet

So what should be done next? I suggest:
* deciding if it makes sense to have an official `wheel` event polyfill (I think it does)
* having someone audit the existing plugins and pick the best solution
* improve the code to meet jquery quality standards
* improve the documentations to meet jquery quality standards
* move the plugin to jquery organization (and transfer package ownership as well)

I'm available to help, anyway.

**Comment by dmethvin** [comment]
If someone would like to take this as a project hosted by the jQuery Foundation, please contact me and we can discuss. I think it would make more sense as polyfill not dependent on jQuery. If that is the case it is not related to this repo (although it could make use of the code as a base) and so I'm closing the ticket.
