### ISSUE TITLE
Page resize limits the scrolling

### ISSUE THREAD

**Issue by addevoldesignstudio** [jquery/jquery-mousewheel#134]
Recently working with this plugin on a responsive layout, it was noticed to be ignoring the mouse-wheel scroll:
1. (on Chrome) after it reached the initial document-height (the screen height while loading the page), before the browser was resized.
2. (on Firefox) from the very beginning. There was a workaround for it by testing for webkit. But without it, the plugin renders the mouse-wheel completely useless.

A simple yet unwelcome remedy would be to call the function, at the end of every browser resize. Even though this is still untested, this does not seem to be the right way to do it. Perhaps you could renew the current-document-height, every time the browser is resized, within the plugin.

A snapshot of the bug:

OS:
    Windows 7
Browsers:
    Chrome 40, Firefox 34
Manual variables (edited within the plugin):
    fricton = 0.8
    stepAmt = 3
Function Call:
    $(function(){ $("body").smoothWheel() })

**Comment by dmethvin** [comment]
Based on the code snippet you posted it sounds like you wanted to post in [jQuery SmoothWheel](https://github.com/fatlinesofcode/jquery.smoothwheel/issues).
