### ISSUE TITLE
Events are triggered for 'mouse wheel down' even though only scroll up is performed on trackpad

### ISSUE THREAD

**Issue by atteeela** [jquery/jquery-mousewheel#135]
Hello,

I'm trying to implement an image zoom in / zoom out feature where the user can scroll up to zoom in and scroll down to zoom out.

The problem is that when the user scrolls down, the scroll events for scroll up are triggered after releasing fingers from the trackpad.  This results in the user being unable to zoom in or out (since it gets 'reset' back to the starting position almost immediately) and results in jitters.

Do you know if there is a way to only get the ACTUAL scroll motion that the user triggered? Right now there seems to be an equal and opposite mouse scroll event fired, regardless of when the user took their fingers off the trackpad.

Thank you,

Platform:

Mac OSX 10.9, Chrome 40, FF 35, others not tested

**Comment by dmethvin** [comment]
This seems more like a support question so you might want to try StackOverflow. The plugin doesn't generate any mousewheeldown events.

**Comment by atteeela** [comment]
My bad, it generates a scroll event with -1 on the y axis. The thing is I never scrolled down.  
There seems to be an equal and opposite reaction for every 'wheel event'. For instance: for every 'wheel up' there's a corresponding 'wheel down' that is generated.
