### ISSUE TITLE
Horizontal scrolling issue

### ISSUE THREAD

**Issue by arjunmenon** [jquery/jquery-mousewheel#137]
Hey
If the mouse is near the bottom scrollbar, but obviously inside the page, scrolling does not happen, strangely.
Only if the mouse is moved towards the content does the scrolling re-initiates.

Strange behavior in any case!

Thanks.

**Comment by dmethvin** [comment]
Are you reporting an issue with the plugin? If so can you please provide enough information to reproduce the problem?

**Comment by arjunmenon** [comment]
Check this out.
http://codepen.io/arjunmenon/full/wBZPRN
The scrolling works but only if the mouse is on the content, text or image. Scrolling will stop on any white space or if mouse near the scrollbar.

**Comment by dmethvin** [comment]
I don't see the plugin being used in that page at all.

**Comment by arjunmenon** [comment]
Why do you say that? It is being use their. Pls check it from Chrome. You can obviously view the source. I have updated the link. It will show the Codepen editor now
http://codepen.io/arjunmenon/pen/wBZPRN

**Comment by dmethvin** [comment]
Sorry, I was looking at the iframe not the inner content. Here is a simple case not using the plugin to see if there are any dead spots in the wheel events: http://codepen.io/anon/pen/mygLpo

**Comment by dmethvin** [comment]
I can't make this reproduce consistently in Chrome. Can you try this Pen with the console open and see if both events are being fired when it seems to get "stuck"? http://codepen.io/anon/pen/JoVvBZ

**Comment by arjunmenon** [comment]
This is the output I am getting - 
```
"plugin 0 1428038455928 -1" index.html:125
"wheel 0 1428038455928" index.html:129
"plugin 0 1428038455944 -1" index.html:125
"wheel 0 1428038456047" index.html:129
"plugin 0 1428038459270 -1" index.html:125
"wheel 0 1428038459270" index.html:129
2 index-e1ea38bff35b91e3163f00f35fc918bc.js:20
1 index-e1ea38bff35b91e3163f00f35fc918bc.js:20
"plugin 0 1428038555875 -1" index.html:125
"wheel 0 1428038555876"
```

So both events do get fired it seems.

Hey btw, I also found this website which implements this plugin. And it also have the same issue.
http://www.kaikkonendesign.fi/columns/

Move the mouse near the bottom scrollbar or near the top grey bar, that is b/w the upper text and grey bar, not over it. You will notice that as you scroll more right, scrolling would cease eventually.

**Comment by dmethvin** [comment]
Just following up, I was able to reproduce this as well but don't have any solution and am not sure whether the cause is inside the plugin.

**Comment by dmethvin** [comment]
It looks like wheel events just stop being generated, which would point to something inside the browser and not the plugin. It seems to happen sooner on Firefox than on Chrome. If there's clearly an issue with the plugin, I can reopen.
