### ISSUE TITLE
Several parts of the website to scroll horizontally

### ISSUE THREAD

**Issue by ASTN1** [jquery/jquery-mousewheel#139]
Hi guys,

I'm developing my new website and would like to use the wonderful Mousewheel plugin. But can't manage to do it as my website is a bit odd.

Basically my website is based on a horizontal format, with 3 DIVs:
- DIV 2 and DIV 3 must be scrollable horizontally
- By default, DIV 2 is hidden
- By default, Mousewheel function apply to DIV 3

![exemple 1](http://nsa38.casimages.com/img/2015/06/11/150611012525205667.png)

- If the user clicks on 'show DIV 2', the DIV appears, and here comes my problem: I want the mousewheel function to apply on DIV 2, no more on DIV 3.

![exemple 1](http://nsa37.casimages.com/img/2015/06/11/150611012525323047.png)

The basic code is:

    $('body, html, *').mousewheel(function(event, delta) {
      $(this).scrollLeft -= (delta * 40);
      event.preventDefault();
    });
  
I adaptated it to:

    $('body, html, *').mousewheel(function(event, delta) {
      if( $('#div2').hasClass('closed')) {
        $('#div3-inner').scrollLeft -= (delta * 40);
      } else {
        $('#div2-inner').scrollLeft -= (delta * 40);
      }
      event.preventDefault();
    });

But specifying a div to scroll doesn't seems to work... Any help?

Here's a JSFiddle: http://jsfiddle.net/L00qqzta/2/

**Comment by dmethvin** [comment]
This is better addressed at StackOverflow.
