### ISSUE TITLE
Minified 4.0 not the same of unminified

### ISSUE THREAD

**Issue by microcipcip** [jquery/jquery-mousewheel#141]
The minified version of this branch is not the same of the unminified version.

**Comment by dmethvin** [comment]
It looks like the copyright header isn't updated, is that what you meant? Or are you saying they are not functionally equivalent?

**Comment by microcipcip** [comment]
They're not the same, the minified version does not have throttle and debounce.

**Comment by dmethvin** [comment]
The unminified version does not have throttle and debounce either, or again I am misunderstanding what you mean. Can you be more specific?

**Comment by dmethvin** [comment]
OIC, you're talking about the 4.x branch and not master. Are you fetching them from the repo directly? It doesn't look like they're published on npm.

**Comment by microcipcip** [comment]
I am talking about the 4.0.x branch

**Comment by dmethvin** [comment]
At the moment 4.0 is strictly experimental, I've opened #145 to track getting it cleaned up and integrated.
