### ISSUE TITLE
Bump version for Bower caches?

### ISSUE THREAD

**Issue by adjohnson916** [jquery/jquery-mousewheel#143]
Relates to #142 and desandro/jquery-bridget#7.

Bower has tag 3.1.12 cached as commit db065e3f8e19fbd351d77b818805744bc165fc28 (see the `bower_components/jquery-mousewheel/.bower.json` property `_resolution.commit` after installing.
But GitHub is saying that tag's commit is c61913ebf569c7a3f086b7fb40d941c282d1ce48.

I'm not sure if that was ever updated through a force push, but hopefully that wouldn't happen often, as changing tags violates ecosystem assumptions.

Luckily Bower still installs the repo, but some tooling I'm building needs to know the actual current tag commit in order to generate links to files, e.g. 
<https://raw.githubusercontent.com/jquery/jquery-mousewheel/db065e3f8e19fbd351d77b818805744bc165fc28/jquery.mousewheel.js>.

I tried `bower cache clear` as suggested in bower/bower#994, but no luck.

Can you bump to version 3.1.13 so Bower is in sync again? Thanks.

**Comment by dmethvin** [comment]
@adjohnson916 Are you seeing the tag correctly for 3.1.13 now?

**Comment by adjohnson916** [comment]
@dmethvin Yes, thanks! On a fresh install, `bower_components/jquery-mousewheel/.bower.json` now has `_resolution.commit` of `67289b6b2aa0066d7d78a5807f520387135ffb22`, which matches https://github.com/jquery/jquery-mousewheel/releases/tag/3.1.13

**Comment by dmethvin** [comment]
Thanks, and sorry for the delay. I had forgotten to `push --tags` and that's what Bower cares about!
