### ISSUE TITLE
It's not working on Linux + Chrome

### ISSUE THREAD

**Issue by pablopareja** [jquery/jquery-mousewheel#147]
I keep getting the exact same values all the time...

> -0 1 53 

any ideas why?

**Comment by dmethvin** [comment]
Sorry I do not. It is possible that mouse wheel events won't work on Linux, or perhaps don't work on specific browsers. You didn't say which Chrome version was affected, or whether you checked multiple ones. You also didn't say which version of Linux you were using. Do you know any other Linux+Chrome users who can help you check this?

**Comment by pablopareja** [comment]
Sorry about that, I forgot to provide those details, here they are:\

I'm using Chrome browser version 44.0.2403.107 (64-bit)
My Linux version is: Ubuntu 15.04 64-bit

**Comment by dmethvin** [comment]
> Do you know any other Linux+Chrome users who can help you check this?

**Comment by pablopareja** [comment]
not really... :confused:

**Comment by dmethvin** [comment]
See if you can find some other users with similar setups. As it stands this isn't enough information to constitute a bug report.
