### ISSUE TITLE
Delta is coming zero for every time

### ISSUE THREAD

**Issue by dsamit** [jquery/jquery-mousewheel#148]
Hey.
I am trying to use "jquery-mousewheel" plug-in.
I am not able to get the delta value as for ever mouse scroll i am getting delta as 0.
I am using JQuery 1.7.2

Please help me out.

Thanks

**Comment by dmethvin** [comment]
Hi! This is the bug tracker, which is only for bug reports. Please ask for programming help on StackOverflow or forum.jquery.com.
