### ISSUE TITLE
jQuery version dependency?

### ISSUE THREAD

**Issue by CaspianRoach** [jquery/jquery-mousewheel#149]
Couldn't find that info on the documentation page. I think this will be useful to folks working on legacy websites.

**Comment by rolandschuetz** [comment]
Version 1.2.6

jquery.mousewheel.js doesn't define any jQuery version and this plugin itself only uses functions from 1.2.6.

**Comment by dmethvin** [comment]
The `bower.json` and `package.json` files specify jQuery version 1.2.2 or higher. We could duplicate that information somewhere else but in general that leads to one or more places being out of date.

**Comment by rolandschuetz** [comment]
You are right, I again failed to use the right repository. For some reason I switched without noticing. Sorry again.
