### ISSUE TITLE
Fix or remove test/browerify

### ISSUE THREAD

**Issue by dmethvin** [jquery/jquery-mousewheel#150]
None of the code in test/browserify has been touched since we adopted the repo. It all looks very out of date, the latest version supported by `jquery-browserify` is 2.0.0 so that's pretty ancient. The bundle.js file is committed to the repo and probably should not be since it's a build output. Browserify is a plumbing thing so it's not proving much about the plugin itself other than that it can be used that way.

**Comment by jzaefferer** [comment]
Let's remove! Can still figure out something better later, if anyone cares.

**Comment by arschmitz** [comment]
:+1: ill do this with my other pr and bump versions
