### ISSUE TITLE
License question 

### ISSUE THREAD

**Issue by DavidCo1** [jquery/jquery-mousewheel#151]
The jquery-mousewheel license contains the following comment:
"All files located in the node_modules and external directories are externally maintained libraries used by this software which have their own licenses; we recommend you read them, as their terms may differ from the terms above."

But I haven't found this folder in the source code. 
is there any external library used in the jquery-mousewheel with other license then MIT?

**Comment by scottgonzalez** [comment]
The source and distribution files don't use any other code. If you're doing development on the plugin and you download the source, then run `npm install`, you'll have external modules installed in the `node_modules` directory for use during development.
