### ISSUE TITLE
Why block scrolling up?

### ISSUE THREAD

**Issue by rolandschuetz** [jquery/jquery-mousewheel#153]
Hello,

I couldn't find any reason why to block scrolling. Could you please add a few infos about this.

Thanks,
Roland

**Comment by dmethvin** [comment]
Can you clarify what you are asking about? It sounds like this is probably a StackOverflow help request and not a bug or docs request but I can't tell.

**Comment by rolandschuetz** [comment]
Sorry, wrong repository. Please close.
