### ISSUE TITLE
fabric.image.fromURL function

### ISSUE THREAD

**Issue by saran110313** [jquery/jquery-mousewheel#158]
hi,
canvas.add(new fabric.Image.url.indexof(circ));
This code error in
Uncaught TypeError: Cannot read property 'indexof' of undefined

i working in node.js in whiteboard project on server to client.this image function add in server site.but not add to client function.how to add this function in server to client..

**Comment by saran110313** [comment]
how to solve this method error Uncaught TypeError: url.indexOf is not a function(png images)

**Comment by dmethvin** [comment]
This does not sound like it's related to the jquery-mousewheel plugin, try asking for help on StackOverflow.

**Comment by saran110313** [comment]
how to separate on path and image id function in board.js and features.js
