### ISSUE TITLE
Not working properly with Edge Browser

### ISSUE THREAD

**Issue by sumitdhingra** [jquery/jquery-mousewheel#161]
Event is fired twice in Edge web browser on a single mouse wheel scroll. Please suggest how this can be handled.
Check this fiddle :  http://jsfiddle.net/CvCc6/

**Comment by dmethvin** [comment]
I've noticed that my trackpad scrolling is twitchy in a lot of Windows 10 apps, not just Edge. Perhaps it's the inertial scrolling? Since this isn't a problem with the plugin (you're not using it in the fiddle) maybe folks on StackOverflow could help?
