### ISSUE TITLE
On vimeo video horizontal scroll issue

### ISSUE THREAD

**Issue by macrofis** [jquery/jquery-mousewheel#166]
Hi!
First, i would like to say thanks to develop this plugin, it is very useful.
Well, I don't how to use it properly, so my apologize for my ignorance.
This is what i have:
`<body>`
`<div class="contenedor">`
`<div class="contenedor-inner">`
`<div class="vimeo">`
`<iframe src="https://player.vimeo.com/video/175424978" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
			<p><a href="https://vimeo.com/175424978">NICELY</a> from <a href="https://vimeo.com/fabienecochard">Fabien Ecochard</a> on <a href="https://vimeo.com">Vimeo</a>.</p>`
`</div>`
`<div class="imagen"></div>`
`<div class="imagen"></div>`
`<div class="imagen"></div>`
`<div class="imagen"></div>`
`</div>`
`</body>`
These divs are in the horizontal way, and the idea is when I scroll down or up, triggers in the horizontal  move.
Actually it works, but when I put the cursor on the vimeo iframe, it doesn't.
Also doesn't work on firefox.

Here is the jquery:

`$("body").mousewheel(function(event, delta) {`
`this.scrollLeft -= (delta * 30);`	
`event.preventDefault();`
`});`
I'll really appreciate for any help.

Greetings from Chile.

**Comment by tonalll** [comment]
<html>

<body>
    <script src="http://code.jquery.com/jquery-1.4.1.js"></script>
    <script src="jquery.mousewheel.js"></script>
<div>
    asdf
    afd
</div>
</body>
<script>
    $("body").mousewheel(function (event, delta) {
        this.scrollLeft -= (delta * 30);
        event.preventDefault();
    });



    $(document).ready(function () {
        $('body', $g).on({
            mousewheel: function (event, delta) {
                var $this = $(this);
                console.info($this.scrollTop());
            }
        });
    });
</script>

</html>

**Comment by tonalll** [comment]
<body>
    <script src="http://code.jquery.com/jquery-1.4.1.js"></script>
    <script src="jquery.mousewheel.js"></script>
<div>
    asdf
    afd
</div>
</body>
<script>
    $(document).ready(function () {
        $("body", $g).on({
            mousewheel: function (event, delta) {
                var $this = $(this);
                console.info($this.scrollTop());
            }
        });
    });
</script>``

**Comment by dmethvin** [comment]
Can you post this question on StackOverflow or the jQuery Forum?
