### ISSUE TITLE
Current bower.json is broken

### ISSUE THREAD

**Issue by nullivex** [jquery/jquery-mousewheel#167]
Hi,

This file is missing the quote on the version. People are trying to install it here http://bowercdn.net/

```
{
	"name": "jquery-mousewheel",
	"version": "3.1.8,
	"main": "./jquery.mousewheel.js",
	"ignore": [
		"*.json",
		"*.markdown",
		"*.txt",
		".*",
		"Gruntfile.js",
		"test"
	],
	"dependencies": {
		"jquery": ">=1.2.2"
	}
}
```

**Comment by dmethvin** [comment]
Here is the bower.json file currently in the repo: 
https://github.com/jquery/jquery-mousewheel/blob/18e3cc17657237220c4dbd68a3fe4f6abdbf7ef8/bower.json

I think you are referring to a 3-year-old commit here, is there a reason you're using that?
https://github.com/jquery/jquery-mousewheel/commit/906ace7c6a7552dfff443fba60744f91fb0d6461

**Comment by nullivex** [comment]
Okay understood I wasnt sure.

I just saw the error pass by in the logs and thought I would mention it. Someone may have been trying to install the older version.
