### ISSUE TITLE
unbind the mousewheel

### ISSUE THREAD

**Issue by NeiChan** [jquery/jquery-mousewheel#171]
I can't find any example but how can I unbind the mousewheel?

What is happening right now : 
I have a About page and a Contact page.

On the About page I'm using this code :
`if(sidescroll) { this.scrollLeft -= (delta * 30); }else{ this.scrollTop -= (delta * 30); }`

If i move my mousewheel it will scroll on the contact page but it has to be disabled.
I tried to do `$('body').unbind('mousewheel');`.

Any idea's?

**Comment by dmethvin** [comment]
The source shows `.unmousewheel()`.
