### ISSUE TITLE
'wheel' Event is widely supported (IE9+)

### ISSUE THREAD

**Issue by oemueller** [jquery/jquery-mousewheel#173]
this Plugin is not working for me anymore. 
Simply using "wheel" Event now via jQuery.
http://devdocs.io/dom_events/wheel

Oliver

**Comment by mgol** [comment]
What do you mean by "not working"? We can't guess what's the problem if you don't share any information...

**Comment by oemueller** [comment]
You're right, sorry. 
It's just that without the Plugin and only using jQuery the and "wheel" Event everything works as it should. IE11+, current Firefox  + Chrome.
So this is more a hint then an issue here ..

**Comment by mgol** [comment]
There are tests ensuring that this plugin works correctly. There may be bugs but every software has them.

Note that the event name used by this plugin is `mousewheel`, not `wheel`.

**Comment by mgol** [comment]
Since there's nothing actionable for us to do with regards to this ticket, I'm going to close it.
