### ISSUE TITLE
Node Module require() compilation issue. 

### ISSUE THREAD

**Issue by veratechnz** [jquery/jquery-mousewheel#174]
I am using jquery mousewheel as an npm node module via a require() call within a gulp and browserify compilaiton.

It is being bundled to a js file with other plugins. All other plugins and libraries have been fine till this point. But jquery-mousewheel will not work within the compiled js file. I can trigger console.logs within the factory code section at the top of the node module jquery-mousewheel.js file. If I explicitly paste the mousewheel.js code within a script tag it works within the application as hoped. 

When it compiles to the bundled.js file, it is there in perfect order. It just does not function within the application via a nodemodule require to a bundled.js file.

I am using jquery-mousewheel in conjunction with jscrollpane.  

Any ideas on what may cause this issue or how to fix?

**Comment by markelog** [comment]
Did you saw https://github.com/jquery/jquery-mousewheel#user-content-using-with-browserify ?
