### ISSUE TITLE
Double scroll

### ISSUE THREAD

**Issue by jcubic** [jquery/jquery-mousewheel#181]
I use mousewheel in [jQuery Terminal](https://github.com/jcubic/jquery.terminal) and I have weird jump when I scroll, it's probably because build in scroll is also triggered, the mousewheel can cancel real mouse wheel event as in this [answer on OS](http://stackoverflow.com/a/4770179/387194)

I think I've fixed the issue by adding:

```
on('wheel', function() { return false; });
```

to the same element as mousewheel plugin.

**Comment by ChCosmin** [comment]
doesn't this cancel the previous on mousewheel ?
