### ISSUE TITLE
middle click

### ISSUE THREAD

**Issue by paolobenve** [jquery/jquery-mousewheel#189]
with modern mice middle click is performed through the central wheel.

However, apparently the plugin converts all wheel events to a delta, i.e. a wheel turn.

How do I detect a simple click?

**Comment by dmethvin** [comment]
This is a StackOverflow question not related to the plugin.

**Comment by paolobenve** [comment]
why is not related to the plugin? without the plugin the middle click event has type click, with the plugin has type mousewheel and (apparently) there is not any way to differentiate a middle click from a wheel turn

**Comment by mgol** [comment]
Clicking via the wheel should trigger a click event, not a wheel one in the same way as clicking on a regular third button on any other mouse.

Do you have a concrete example where that’s not the case?

**Comment by paolobenve** [comment]
I have in my code something like:

```
("#selector").on('contextmenu click mousewheel', function(ev, delta) {
  console.log(ev.type);
  ....
});
```

clicking in selector with left or right button, ev.type=click, with middle button ev.type=mousewheel

I'm seeing that the plugin replace type click with mousewheel, and no track of original type is left.

A solution could be to save all the changed elements in an array, naming it "originals", or something similar. This way the code could manage the middle click.

**Comment by mgol** [comment]
As you can see, there's no mention of `click` in the source of this plugin. I'd guess there must be something else going on in your code.

As a general rule, if you think there's a bug please prepare a minimal (!) jsFiddle or JSBin example so that we can quickly run it without needing to set anything up manually. Otherwise it's really hard for us to spend time on the issue, especially that often there's no bug but we can't see that before we see a test case which we would have to take time to create by ourselves.

**Comment by paolobenve** [comment]
no mention of click, but at line 103:

`event.type = 'mousewheel';`

overwrites event.type, whose value is 'click' before that line

**Comment by mgol** [comment]
We still don’t have a test case, though.

**Comment by paolobenve** [comment]
https://jsfiddle.net/paolobenve/dkwnmc88/19/ you can see all the effects of mouse wheel on the event:

- rotating: deltaX -> 0,  deltaY -> 1/-1
- clicking: deltaY -> 0, deltaX -> 1/-1
- clicking aside (my mouse permits it): deltaY -> 0, deltaX -> 1/-1

checking deltaX/Y permits to detect a rotation, but not to decide wheter a click or a left/right click has been issued

**Comment by paolobenve** [comment]
@dmethvin, `event.originalEvent` hasn't anything significative

**Comment by dmethvin** [comment]
If it's not in the event the plugin receives then the plugin cannot provide the information.
