### ISSUE TITLE
Violation in newer versions of Chrome

### ISSUE THREAD

**Issue by nurikabe** [jquery/jquery-mousewheel#195]
`[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Comment by mgol** [comment]
Duplicate of #168 & #183. We'll deal with it once https://github.com/jquery/jquery/issues/2871 is fixed.
