### ISSUE TITLE
Sometimes you try to access a cdn in cloudflares

### ISSUE THREAD

**Issue by martinmurciego** [jquery/jquery-mousewheel#196]
Sometimes you try to access a cdn into cloudflares: https://cdnjs.com/libraries/jquery-mousewheel and throw an error. I have seen this error in the chromium javascript console especially when the internet connection speed becomes slow. So it does not access the library hosted locally in the directory of javascript and css files but seeks to access the cdn. How do I modify this unwanted behavior?

**Comment by dmethvin** [comment]
We don't control the Cloudflare CDN.
