### ISSUE TITLE
npmjs download not working

### ISSUE THREAD

**Issue by seanr** [jquery/jquery-mousewheel#197]
I've got a pretty big package.json and all of it seems to work until it gets to this package. You see it hang for a bit and then the following:

```
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2018-12-05T22_13_43_833Z-debug.log
```

I tried a `npm cache clean --force` and rerunning, but no dice - craps out on the same one each time, leading me to believe the upload may be corrupt. Our package.lock contains the following:

```
    "jquery-mousewheel": {
      "version": "3.1.13",
      "resolved": "https://npm.tfanet.org/jquery-mousewheel/-/jquery-mousewheel-3.1.13.tgz",
      "integrity": "sha1-BvAzXxbjU6aV5yBr9QUDy1I6buU="
    },
```

We're getting that as a dependency of something else and I'm the back-end guy, so I don't want to try overriding that version.

**Comment by dmethvin** [comment]
This doesn't sound like a bug with jquery-mousewheel. Normally the "resolved" entry will be registry.npmjs.org unless you're running your own mirror of the repo, so you might want to look into that since yours says npm.tfanet.org.

**Comment by seanr** [comment]
@dmethvin that registry is just a passthrough to registry.npm.js for all but one locally hosted package. The others all work fine, just this one fails.
