### ISSUE TITLE
This code is still using bind() and unbind()

### ISSUE THREAD

**Issue by ayumihamsaki** [jquery/jquery-mousewheel#200]
Hi,

According to jQuery doc's `.bind()` is not used anymore and you should switch to `.on()` as per doc's found here: https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated

Your code line is here: https://github.com/jquery/jquery-mousewheel/blob/33dc8f1090da2eaadbca8e782965d7fd6c28db42/jquery.mousewheel.js#L84

Also according to jQuery doc's `.unbind()` is not used anymore and you should switch to `.off()` as per doc's found here: https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnunbind-is-deprecated

Your code line is here: https://github.com/jquery/jquery-mousewheel/blob/33dc8f1090da2eaadbca8e782965d7fd6c28db42/jquery.mousewheel.js#L88

**Comment by dmethvin** [comment]
Fixed in f7d64c76cffbeb127f20c8047035893e504d910a

**Comment by ayumihamsaki** [comment]
@dmethvin Thanks for adding my pr. Is it possible to update the version number of this repo as we are using jquery-mousewheel in our repo. The last release is 3.1.13 dated 19 Jun 2015 (which is probably wrong and has not been updated). Thanks in advance.

**Comment by dmethvin** [comment]
Yes, I am working on updating all the build and test scripts now. Once that is done I will publish 3.2.0 to npm. That will also fix the issue with the minified file being missing.

**Comment by ayumihamsaki** [comment]
Cool, look forward to it. 👍
