### ISSUE TITLE
How can i check scroll up or down event?

### ISSUE THREAD

**Issue by BibinFrancis** [jquery/jquery-mousewheel#205]
how can i check whether the scroll event is up or down inside a div using class name. overflow is hidden for the body.

I have already used a code and it does not works; Here is the code i used

`$(function() {
        $('body').bind('mousewheel', function(event) {
          event.preventDefault();
          var scrollTop = this.scrollTop;
          this.scrollTop = (scrollTop + ((event.deltaY * event.deltaFactor) * -1));
          alert(event.deltaY);
          console.log(event.deltaY, event.deltaFactor, event.originalEvent.deltaMode, event.originalEvent.wheelDelta);
        });
      });`

**Comment by dmethvin** [comment]
This isn't a bug report, try Stackoverflow.com.
