### ISSUE TITLE
mousewheel event doesn't work on Safari (tested on 5.1.7) for windows.

### ISSUE THREAD

**Issue by gui-yem** [jquery/jquery-mousewheel#90]
Hi, Thanks for this excelent plugin (very usefull).
It seems that mousewheel event doesn't work on Safari (tested on 5.1.7) for windows. is there a way to fix it properly ?
Thanks.

**Comment by griii2** [comment]
I was fighting with similar issue but my problem was https://bugs.webkit.org/show_bug.cgi?id=124139
