### ISSUE TITLE
pixel scroll

### ISSUE THREAD

**Issue by yukulele** [jquery/jquery-mousewheel#95]
I would like to know if a mouse event is generated from classic wheel device (logitech/microsoft mouse) or a pixel scroll device (Apple magic mouse/trackpad)

How to reliably differentiate them ?

``` javascript
$('#my_elem').on('mousewheel', function(event) {
    console.log(event.fromPixelScroll); //boolean
});
```

**Comment by dmethvin** [comment]
@yukulele So the feature being requested here is to detect the difference between devices on the same computer? Can you do some legwork to provide data about the events generated by each and the properties in the event objects? If they differ it may be possible to distinguish them.
